[package]
name = "hddllfrt"
version = "1.0.1"
edition = "2024"
authors = ["DevNergis"]
description = "Cross-platform HDD Low Level Format Tool"
license = "AGPL-3.0-or-later"
repository = "https://github.com/DevNergis/HDDLLFRT"

[dependencies]
dialoguer = "0.11"
indicatif = "0.17"
console = "0.15"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
nix = { version = "0.27", features = ["fs", "ioctl", "mount"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming",
    "Win32_Devices_DeviceAndDriverInstallation",
] }
widestring = "1.0"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
plist = "1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
debug = false
incremental = false
overflow-checks = true
